dist: trusty
sudo: required
language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
- pip install pyinstaller
script:
- pyinstaller -F -y -n yarn_exporter yarn_exporter.py
deploy:
  provider: releases
  api_key:
    secure: b4ov45tSASBB1AJ282JMuEhOpsqhmdHuKeKOB/FnyjlELFxzg+wOgC5tTp3ksoBWzGyp4UoA0547xxt21iKcm1KD7Oz9+yiurYWj6kdclQuZ65EK1vO9Kg8Mu1Tu+vyVdt2DBBvZazYJptgyjfmWeZyBkdQbZFtpC6LMj1l+YkEkRiP8BG+c1/bI/e1PtAhV5cXTNnak2LT3VL8KsKIs97XURmX7VKGL9SSMQBbqg9vDyZH2d0/D+UQVGCdx2vpR3FL9cuDzNaqm/3iVHoyB6+kk6Dt2Cld5jrDomFDdSbhAAD9dFqduqK4PHHk7IxO7KI0lqqtfTm/EMdVpY9OQGP2I4WgTWsNPt4PiLEWjuFScKApQlnFwfOer1nAciSCBPBJaP2FVBjf4FGQtGUeV+njFfzrcS5bGVS/1wCF9HA4myYwqUaGdNlsLgfqFIpzr2kA5q3n41Y2EO6Wu6ZvvHH8NC7eDZH5ju5nol+3lKjsow3b/FmGvSv4U3SMHS47h4LEFu1y2h9t0gc2W6Qn1Iw5r7TybxjnahrzB0atwk+gEaU/8mgUGhS6hJ3Plcbn65uSI0sdtUb9vYLoJ1E5RfGbQNMax8iLoUZgYW4GqAVs3tnqwpJVF0rzAzt0Qc3pc5oGrVT8A516QfPql+dJeDakhd6Rn5VfIoNlznZ90UiE=
  file: dist/yarn_exporter
  skip_cleanup: true
  on:
    repo: soloradish/yarn_exporter
